# --- !Ups

CREATE TABLE relations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actionId BIGINT NOT NULL,
  label VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
)
  ENGINE=MYISAM;

# --- !Downs

DROP TABLE relations;