# --- !Ups

CREATE TABLE consequences (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  label VARCHAR(20) NOT NULL,
  severity DOUBLE NOT NULL,
  effectID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(id)
)
  ENGINE=MYISAM;

# --- !Downs

DROP TABLE consequences;